export const MQTT_FIXTURE = "MQTT_FIXTURE" ;
export const MQTT_SUBSCRIBED = "MQTT_SUBSCRIBED";
export const MQTT_FAIL = "MQTT_FAIL";
export const MQTT_RECONNECT = "MQTT_RECONNECT";
export const ADD_FIXTURE = "ADD_FIXTURE";
export const UPDATE_FIXTURE = "UPDATE_FIXTURE"